version: '3'

services:
  dockerfile:
    build:
      context: ../../
      dockerfile: ./admin-api/docker/node/Dockerfile
    image: dockerfile
    container_name: dockerfile
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - EXTERNAL_URL
      - HOSTNAME
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
